# Generated by Django 4.2.1 on 2023-06-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='trainings.typeexercise'),
        ),
    ]
